import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import "./globals.css";
import Footer from './components/Footer'
import Header from "./components/Header";
import ReduxProvider from "./store/Provider";
import AuthModal from "./components/AuthModal";
import WishlistModal from "./components/WishlistModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
        <ReduxProvider>

        <Header />
        {children}
        <Footer />
        <AuthModal />
        <WishlistModal />
        </ReduxProvider>
      </body>
    </html>
  );
}
